### PR TITLE
Fix to always use json when sending a PUT/POST

### LINKED ISSUE #199: having issues logging in
Getting the following in HASS that I assume is a surepy issue (well, a sure petcare issue really I would guess)

2023-12-10 13:30:26.544 ERROR (MainThread) [surepy.client] 🐾 �[38;2;255;26;102m·�[0m GET app.api.surehub.io/api/me/start: 401 | <ClientResponse(https://app.api.surehub.io/api/me/start) [401 Unauthorized]>
2023-12-10 13:30:28.024 DEBUG (MainThread) [surepy.client] 🐾 �[38;2;0;255;0m·�[0m GET app.api.surehub.io/api/me/start | 6
2023-12-10 13:30:28.025 DEBUG (MainThread) [homeassistant.components.surepetcare] Finished fetching surepetcare data in 1.623 seconds (success: False)
2023-12-10 13:30:28.025 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Sure Petcare' for surepetcare integration could not authenticate: Invalid username/password

### PR DESCRIPTION
**Pull request by ashleigh-hopkins**
Disclaimer, I've never written any python before... and I didn't test that any command and control actions work 😅

Should fix #199

### CODE REVIEW

**Comment by benleb** [comment]
oh hey :D thanks you! looks good on first view, will check it tomorrow and merge :)

great to get a contribution from you! 🙌 😄

**Comment by dieriver** [comment]
I have tested this fix, and it seems it works. At least the PUT queries now work (specifically, u tried using the `client._set_lock_state` function, and the server can handle it correctly.

**Comment by jdrews** [comment]
I have also tested this branch and can confirm that it restores API connectivity. On the `v0.9.0a0` release I get a "[415 Unsupported Media Type]" and DENY back from surehub.io. With this PR I am able to perform queries to the surehub.io API again.

**Comment by ivo-toby** [comment]
I replaced the lib in my Home-assistant install and it works like a charm! Just in time for new-years so I can keep the cats indoors while I'm abroad.. Thanks a lot!

**Comment by blair287** [comment]
> I replaced the lib in my Home-assistant install and it works like a charm! Just in time for new-years so I can keep the cats indoors while I'm abroad.. Thanks a lot!

How do you do that please?

**Comment by ivo-toby** [comment]
> > I replaced the lib in my Home-assistant install and it works like a charm! Just in time for new-years so I can keep the cats indoors while I'm abroad.. Thanks a lot!
> 
> How do you do that please?

Depends on your setup, ymmv. 
I am running HassOS (in proxmox) with the advanced SSH plugin. I don't upgrade Home-assistant that often, so I am not on the latest version!

So what I did:
-  ssh'ed to the instance
- list all running containers with `docker ps` and searched for the `ghcr.io/home-assistant/qemux86-64-homeassistant` container. 
- got shell with `docker exec -it [container-id] bash`
- cloned this repo into `/root`
- search for the location of `surepy` with `pip show surepy`, on my setup it was in `/usr/local/lib/python3.11/site-package/surepy`
- replaced `/usr/local/lib/python3.11/site-package/surepy` with the one in `/root/surepy/surepy`

That should do the trick.  I do recommend backing up the original `surepy` folder in `/usr/local/lib/python3.11/site-package/`. Also; if you update Home-assistant and the fixes has not been merged you will need to do this again.

**Pull request merged**
