### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by Danielhiversen**
This code seems unnecessary? And then trigger unnecessary requests to petcare

### CODE REVIEW

**Comment by Danielhiversen** [comment]
@benleb

**Comment by benleb** [comment]
sorry @Danielhiversen! I will check this, at a first view it seems the drinking/feeding data would be missing? but I will have a deeper look!

that's the log of one "update round" from my home assistant, I don't think we can sort out one of them 🤨
- the first is to the general /start endpoint
- then the next three are for each household I have in my account
- the last four are to the timeline endpoint (to get the felaqua data) which I thought I would have to paginate (but its turning out the problem is somewhere else maybe, see https://community.home-assistant.io/t/sureflap-connect-pet-door/41488/607?u=benleb). The pagination code was never pushed so all public versions would have just a single call there
image

**Comment by Danielhiversen** [comment]
Could you point me to where in the code the call to get_actions is used? 
The return value is not used and I do not see that the function set any value?


I only have the flap and the code change works fine for me, and the number of requests is 50%.

**Comment by benleb** [comment]
the data received will be saved to `self.entities[device_id]` [here](https://github.com/benleb/surepy/blob/4f368776e30d699bfe19dd4504ea36162567f840/surepy/__init__.py#L193) for example. But I absolutely agree that this is really easy to overlook and an awful style...  🙄

> I only have the flap and the code change works fine for me, and the number of requests is 50%.

that's why I check if for example there is a Felaqua in the household at all before making that request. But due to their "interesting" API style, that's not possible with the other devices afaik... 

How many calls per Update did you see before/after the code change?

**Comment by Danielhiversen** [comment]
Ahh, I see.
But is the data in `_data["move"]` used?

**Comment by benleb** [comment]
`"move"` is currently not in used (but maybe will be for the upcoming device trackers for pets), but `"lunch"` is (entities/devices.py:135) :)

so for your case, you are right :D but for people with a feeder that would be a problem... so what do you think about doing the `get_actions(..)` call just for households with a feeder (like it is done for "felaqua households") for now? If the `"move"` data will be used eventually, this can easily changed back to do it for every household and for the moment we wont do any useless calls anymore. Or do you have another idea? :)

**Comment by Danielhiversen** [comment]
Ok, I see.
If I understand it correctly get_actions is needed to detect the connected devices and update some of them? 
So if the user only has a flap, it should only be required to do get_actions once?

I am closing this, since it is not a working solution

**Pull request closed without merging**
